const clothes = [
    {
        id:       1,
        image:    '/src/assets/tshirt-img.png',
        isNew:    true,
        title:    'Футболка "Эволюционируй или сдохни"',
        price:    220,
        size:     'Размеры S/M/L',
        hasSize:  true,
        hasColor: true,
        details:  'Брендированная футболка от Qazaq Republic. Материал: Хлопок 80%, Вискоза 20%',
    },
    {
        id:       2,
        image:    '/src/assets/tshirt-img.png',
        isNew:    false,
        title:    'Футболка "Эволюционируй или сдохни" Limited',
        price:    220,
        size:     'Оверсайз',
        hasColor: true,
        details:  'Брендированная футболка от Qazaq Republic. Материал: Хлопок 80%, Вискоза 20%. Переиздание',
    },
    {
        id:       3,
        image:    '/src/assets/sweatshirt-img.png',
        isNew:    false,
        title:    'Толстовка "Kolesa Team post-COVID"',
        price:    290,
        size:     'Размеры S/M/L',
        hasColor: true,
        details:  'Брендированная толстовка от Qazaq Republic. Материал: Хлопок 80%, Вискоза 20%.',
    },
    {
        id:       4,
        image:    '/src/assets/sweatshirt-img.png',
        isNew:    false,
        title:    'Толстовка "Kolesa Team pre-COVID"',
        price:    280,
        size:     'Размеры S/M/L',
        hasColor: true,
        details:  'Брендированная толстовка от Qazaq Republic. Материал: Хлопок 80%, Вискоза 20%.',
    },
    {
        id:       5,
        image:    '/src/assets/hoodie-img.png',
        isNew:    false,
        title:    'Худи "Kolesa Minimal"',
        price:    300,
        size:     'Размеры S/M/L',
        hasColor: true,
        details:  'Минималистичная худи от Qazaq Republic. Материал: Хлопок 80%, Вискоза 20%. Минимализм во всей красе',
    },
    {
        id:       6,
        image:    '/src/assets/hoodie-img.png',
        isNew:    true,
        title:    'Худи "Kolesa Minimal vol.2"',
        price:    320,
        size:     'Размеры S/M/L',
        hasColor: true,
        details:  'Минималистичная худи от Qazaq Republic. Материал: Хлопок 80%, Вискоза 20%. Переиздание.',
    },
];

const accessories = [
    {
        id:       7,
        image:    '/src/assets/bottle-img.png',
        isNew:    false,
        title:    'Бутылка прозрачная "Kolesa Water"',
        price:    150,
        size:     'Объем 0.5/0.7/1 л.',
        hasColor: false,
        details:  'Брендированная бутылка от Qazaq Republic из прозрачного пластика.',
    },
    {
        id:       8,
        image:    '/src/assets/bottle-img.png',
        isNew:    true,
        title:    'Бутылка матовая "Kolesa Water"',
        price:    160,
        size:     'Объем 0.5/0.7/1 л.',
        hasColor: false,
        details:  'Брендированная бутылка от Qazaq Republic из матового пластика.',
    },
    {
        id:       9,
        image:    '/src/assets/cap-img.png',
        isNew:    true,
        title:    'Бейсболка "Kolesa Simple vol.2"',
        price:    200,
        size:     'Размеры S/M/L',
        hasColor: true,
        details:  'Брендированная бейсболка от Qazaq Republic. Материал: Хлопок 80%, Вискоза 20%. Переиздание.',
    },
    {
        id:       10,
        image:    '/src/assets/cap-img.png',
        isNew:    false,
        title:    'Бейсболка "Kolesa Simple"',
        price:    200,
        size:     'Размеры S/M/L',
        hasColor: true,
        details:  'Брендированная бейсболка от Qazaq Republic. Материал: Хлопок 80%, Вискоза 20%.',
    },
    {
        id:       11,
        image:    '/src/assets/notebook-img.png',
        isNew:    false,
        title:    'Блокнот "Kolesa Thoughts Out"',
        price:    220,
        size:     'Объем 100 стр.',
        hasColor: false,
        details:  'Брендированный блокнот от Qazaq Republic на 100 страниц.',
    },
    {
        id:       12,
        image:    '/src/assets/notebook-img.png',
        isNew:    false,
        title:    'Блокнот "Kolesa Thoughts Out"',
        price:    180,
        size:     'Объем 50 стр.',
        hasColor: false,
        details:  'Брендированный блокнот от Qazaq Republic на 50 страниц.',
    },
];

export { clothes, accessories };
